version: "3.8"
services:
  redis:
    image: redis:7.2.4
    ports:
      - 6379

  db:
    image: postgres:16.1
    ports:
      - 5432
    environment:
      POSTGRES_DB: bungledb
      POSTGRES_PASSWORD: bunglepassword
      POSTGRES_USER: bungleuser
