version: "3.8"
services:
  db:
    image: postgres:16.1
    ports:
      - 5432
    environment:
      POSTGRES_DB: bungledb
      POSTGRES_PASSWORD: bunglepassword
      POSTGRES_USER: bungleuser

  redis:
    image: redis    
    ports: 
      - 6379
