FROM amazoncorretto:21 as build
WORKDIR app
COPY gradlew .gradle *.gradle.kts .
RUN ./gradlew bootJar

FROM amazoncorretto:21 as layered
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
RUN java -Djarmode=layertools -jar app.jar extract

# I will have to look into permissions later
FROM amazoncorretto:21 as prod
ENV SPRING_PROFILES_ACTIVE=prod
WORKDIR app
COPY --from=layered app/dependencies .
COPY --from=layered app/spring-boot-loader .
COPY --from=layered app/snapshot-dependencies .
COPY --from=layered app/application .
USER 1000
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
