version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bungle
      - SPRING_DATASOURCE_USERNAME=bungleuser
      - SPRING_DATASOURCE_PASSWORD=bunglepass
    depends_on:
      - db
    volumes:
      - backend_tmp:/tmp
