spring:
  profiles:
    default: "dev"
---
spring:
  application:
    name: Bungle
  config:
    activate:
      on-profile: "dev"
  devtools:
    livereload:
      enabled: true
    restart:
      poll-interval: 2s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  session:
    redis:
      flush-mode: on-save
      namespace: spring:session # Namespace for keys used to store sessions.
  data:
    redis:
      host: localhost
      port: 6379

server: 
  servlet:
    session:
      timeout: 3600s

logging:
  level:
    org:
      springframework:
        security: TRACE
---
# java -jar app.jar -Dspring.profiles.active=prod
# or
# SPRING_PROFILES_ACTIVE=prod java -jar app.jar
spring:
  config:
    activate:
      on-profile: "prod"
